### ISSUE TITLE
通过 chunkfiles 来声明 script entry 存在缺陷

### ISSUE THREAD

**Issue by howel52** [eynol/qiankun-dev-webpack-plugin#4]
结合 HMR 可能会给多个 `script` 打上 `entry attribute`，会造成 `import-html-entry` 的解析异常，见[这里](https://github.com/kuitos/import-html-entry/blob/11112493de4435f2e4e5aae7d3f937a8740d1555/src/process-tpl.js#L117)

同时也可能会造成入口文件识别的不准确，出现误判，比如给 `debug/lib.js` 打上了 `entry` 等不符合预期的结果。

或许可以提供一个 `entryRule` 的声明入口，当默认行为不符合预期时，由业务方完全受控。

**Comment by eynol** [comment]
我刚才试用的时候也发现了，然后想的还是用注释掉的那段代码去取出entry的名称来， 然后在加上entry attribute的时候 从后往前找 ，只找一个脚本作为entry的入口。

**Comment by howel52** [comment]
> 然后在加上entry attribute的时候 从后往前找 ，只找一个脚本作为entry的入口

嗯嗯 这样也可以。
