### ISSUE TITLE
umd bundle 产物是不是叫 appName 就可以了

### ISSUE THREAD

**Issue by howel52** [eynol/qiankun-dev-webpack-plugin#6]
https://github.com/eynol/qiankun-dev-webpack-plugin/blob/a3a6202f0698c04ea8bb4a7cb9043700c85c1e38/src/index.ts#L60

感觉是不是叫 `${appName}` 就可以了

**Comment by eynol** [comment]
是的，那个library不会使用[name]

**Comment by howel52** [comment]
https://github.com/eynol/qiankun-dev-webpack-plugin/commit/d3b3cdc43120f77c9a169cd02e92e054f4ff27e5

close
